name: Deploy the backend
on:
  push:
    branch: [ main ]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB.USERNAME }}
          password: ${{ secrets.DOCKERHUB.TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.api
          push: true
          tags: rajputshashank/user-app-api:${{ github.sha }}